services:
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    ports:
      - "8081:8081"
    volumes:
      - nexus-data:/nexus-data
    environment:
      - NEXUS_SECURITY_RANDOMPASSWORD=false
      - NEXUS_SECURITY_ADMINPASSWORD=admin123
    networks:
      - nexus_network
    restart: unless-stopped

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
     # - "50000:50000"
    environment:
      - NEXUS_USER=admin
      - NEXUS_PASSWORD=admin123
      - NEXUS_URL=http://nexus:8081
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - nexus_network
    restart: unless-stopped

volumes:
  nexus-data:
  jenkins_home:

networks:
  nexus_network:
